services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: teleanki
      POSTGRES_PASSWORD: na_gorshke_sidel_korol
      POSTGRES_DB: teleanki
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
